version: '3.8'

services:
  web:
    build:
      context: https://github.com/yogi7777/tickets.git#main
      dockerfile: Dockerfile
    container_name: php_app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - app_data:/var/www/html
      - uploads_data:/var/www/html/uploads
    environment:
      - DB_HOST=db
      - DB_NAME=projekt_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_NAME=${SMTP_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    depends_on:
      - db

  db:
    image: mariadb:latest
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: projekt_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  db_data:
  app_data:
  uploads_data:
