version: '3.8'

services:
  web:
    build:
      context: https://github.com/dein-user/dein-repo.git#main
      dockerfile: docker/Dockerfile
    container_name: php_app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - app_data:/var/www/html
      - uploads_data:/var/www/html/uploads
    environment:
      - DB_HOST=db
      - DB_NAME=projekt_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: projekt_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
  app_data:
  uploads_data:
